apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  labels:
    app: customer-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
        - name: customer-service
          image: customer-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
  ---
  apiVersion: v1
  kind: Service
  metadata:
    name: customer-service
    namespace: default
  spec:
    selector:
      app: customer-service
    ports:
      - protocol: TCP
        port: 8083
        targetPort: 8083
    type: NodePort